# Generated by Django 5.2.12 on 2026-03-21 14:51

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import planner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', planner.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(db_index=True, default='login', max_length=32)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('status', models.CharField(db_index=True, default='sent', max_length=16)),
                ('request_ip', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='planner_aut_email_65a683_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSessionRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(default=planner.models.generate_hex_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('title', models.CharField(default='未命名会话', max_length=120)),
                ('status', models.CharField(db_index=True, default='idle', max_length=48)),
                ('messages', models.JSONField(default=list)),
                ('confirmed_constraints', models.JSONField(default=dict)),
                ('latest_result', models.JSONField(blank=True, null=True)),
                ('active_turn_id', models.CharField(blank=True, max_length=32, null=True)),
                ('latest_summary', models.CharField(blank=True, max_length=400)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatTurnRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turn_id', models.CharField(default=planner.models.generate_hex_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('input_mode', models.CharField(default='chat', max_length=16)),
                ('user_message', models.JSONField()),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('confirmed_constraints', models.JSONField(default=dict)),
                ('steps', models.JSONField(default=list)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('assistant_message', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_records', to='planner.chatsessionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerRunRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_id', models.CharField(default=planner.models.generate_hex_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('request_payload', models.JSONField()),
                ('steps', models.JSONField(default=list)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningJob',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.CharField(default=planner.models.generate_hex_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, max_length=24)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('timeout_seconds', models.PositiveIntegerField(default=90)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict)),
                ('chat_turn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_job', to='planner.chatturnrecord')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_jobs', to=settings.AUTH_USER_MODEL)),
                ('planner_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_job', to='planner.plannerrunrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_id', models.CharField(default=planner.models.generate_hex_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未命名方案', max_length=160)),
                ('status', models.CharField(db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('constraints_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='planner.chatsessionrecord')),
                ('source_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='planner.chatturnrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('guest_token', models.CharField(blank=True, max_length=256)),
                ('session_id', models.CharField(blank=True, max_length=32)),
                ('turn_id', models.CharField(blank=True, max_length=32)),
                ('plan_id', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='planner_ana_event_t_dfffd0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsessionrecord',
            index=models.Index(fields=['owner', '-updated_at'], name='planner_cha_owner_i_c5b82a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessionrecord',
            index=models.Index(fields=['guest_token', '-updated_at'], name='planner_cha_guest_t_8fdcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatturnrecord',
            index=models.Index(fields=['session', 'created_at'], name='planner_cha_session_e770b5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatturnrecord',
            index=models.Index(fields=['status', 'created_at'], name='planner_cha_status_4bf42d_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerrunrecord',
            index=models.Index(fields=['owner', '-updated_at'], name='planner_pla_owner_i_3c573d_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerrunrecord',
            index=models.Index(fields=['guest_token', '-updated_at'], name='planner_pla_guest_t_203619_idx'),
        ),
        migrations.AddIndex(
            model_name='planningjob',
            index=models.Index(fields=['status', 'created_at'], name='planner_pla_status_37eb98_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplanrecord',
            index=models.Index(fields=['owner', '-updated_at'], name='planner_tri_owner_i_cad2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplanrecord',
            index=models.Index(fields=['source_session', 'version'], name='planner_tri_source__9033a3_idx'),
        ),
    ]
