# Generated by Django 5.2.12 on 2026-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_authcode_failed_attempts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCode',
        ),
        migrations.RemoveField(
            model_name='plannerrunrecord',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='planningjob',
            name='planner_run',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='planner_ana_event_t_300ec4_idx',
            old_name='planner_ana_event_t_dfffd0_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsessionrecord',
            new_name='planner_cha_owner_i_fda00e_idx',
            old_name='planner_cha_owner_i_c5b82a_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsessionrecord',
            new_name='planner_cha_guest_t_7f70c1_idx',
            old_name='planner_cha_guest_t_8fdcaf_idx',
        ),
        migrations.RenameIndex(
            model_name='chatturnrecord',
            new_name='planner_cha_session_f832c9_idx',
            old_name='planner_cha_session_e770b5_idx',
        ),
        migrations.RenameIndex(
            model_name='chatturnrecord',
            new_name='planner_cha_status_d5a48a_idx',
            old_name='planner_cha_status_4bf42d_idx',
        ),
        migrations.RenameIndex(
            model_name='planningjob',
            new_name='planner_pla_status_313cf6_idx',
            old_name='planner_pla_status_37eb98_idx',
        ),
        migrations.RenameIndex(
            model_name='tripplanrecord',
            new_name='planner_tri_owner_i_9a9804_idx',
            old_name='planner_tri_owner_i_cad2f0_idx',
        ),
        migrations.RenameIndex(
            model_name='tripplanrecord',
            new_name='planner_tri_source__b16f00_idx',
            old_name='planner_tri_source__9033a3_idx',
        ),
        migrations.RemoveField(
            model_name='chatsessionrecord',
            name='messages',
        ),
        migrations.AddField(
            model_name='planningjob',
            name='guest_token',
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='result_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='analyticsevent',
            table='planner_analytics_event',
        ),
        migrations.AlterModelTable(
            name='chatsessionrecord',
            table='planner_chat_session',
        ),
        migrations.AlterModelTable(
            name='chatturnrecord',
            table='planner_chat_turn',
        ),
        migrations.AlterModelTable(
            name='planningjob',
            table='planner_planning_job',
        ),
        migrations.AlterModelTable(
            name='tripplanrecord',
            table='planner_trip_plan',
        ),
        migrations.AlterModelTable(
            name='user',
            table='planner_user',
        ),
        migrations.DeleteModel(
            name='PlannerRunRecord',
        ),
    ]
