# Generated by Django 5.2.12 on 2026-03-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_delete_authcode_remove_plannerrunrecord_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
    ]
