# Generated by Django 5.2.12 on 2026-04-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_remove_unused_schema_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgebaserecord',
            new_name='planner_kno_is_defa_8f7d9a_idx',
            old_name='planner_kno_is_defa_11e9d3_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaserecord',
            new_name='planner_kno_slug_ac3103_idx',
            old_name='planner_kno_slug_366aad_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocumentrecord',
            new_name='planner_kno_knowled_7fc922_idx',
            old_name='planner_kno_knowled_998f56_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocumentrecord',
            new_name='planner_kno_knowled_3c4e43_idx',
            old_name='planner_kno_knowled_f53103_idx',
        ),
    ]
