from django.urls import path

from planner.api.views import (
    assistant_conversation_view,
    assistant_conversations_view,
    auth_me_view,
    chat_session_view,
    chat_sessions_view,
    chat_turn_view,
    create_chat_turn_view,
    create_assistant_message_view,
    create_assistant_message_stream_view,
    create_chat_turn_stream_view,
    health_check,
    knowledge_dashboard_view,
    knowledge_overview_view,
    knowledge_document_view,
    knowledge_document_retry_view,
    knowledge_documents_view,
    knowledge_reindex_view,
    logout_view,
    password_login_view,
    plan_status_view,
    plan_trip_view,
    plan_trip_stream_view,
    recent_assistant_conversation_view,
    recent_chat_session_view,
    resume_trip_plan_view,
    save_trip_plan_view,
    save_run_plan_view,
    send_auth_code_view,
    set_password_view,
    trip_plan_view,
    trip_plans_view,
    verify_auth_code_view,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/codes/", send_auth_code_view, name="auth-code-send"),
    path("auth/login/verify/", verify_auth_code_view, name="auth-login-verify"),
    path("auth/login/password/", password_login_view, name="auth-login-password"),
    path("auth/me/", auth_me_view, name="auth-me"),
    path("auth/password/", set_password_view, name="auth-password-set"),
    path("auth/logout/", logout_view, name="auth-logout"),
    path("assistant/conversations/", assistant_conversations_view, name="assistant-conversation-list-create"),
    path("assistant/conversations/recent/", recent_assistant_conversation_view, name="assistant-conversation-recent"),
    path("assistant/conversations/<str:conversation_id>/", assistant_conversation_view, name="assistant-conversation"),
    path("assistant/conversations/<str:conversation_id>/messages/", create_assistant_message_view, name="assistant-message-create"),
    path(
        "assistant/conversations/<str:conversation_id>/messages/stream/",
        create_assistant_message_stream_view,
        name="assistant-message-create-stream",
    ),
    path("knowledge/", knowledge_dashboard_view, name="knowledge-dashboard"),
    path("knowledge/overview/", knowledge_overview_view, name="knowledge-overview"),
    path("knowledge/documents/", knowledge_documents_view, name="knowledge-documents"),
    path("knowledge/documents/<str:document_id>/", knowledge_document_view, name="knowledge-document"),
    path("knowledge/documents/<str:document_id>/retry/", knowledge_document_retry_view, name="knowledge-document-retry"),
    path("knowledge/reindex/", knowledge_reindex_view, name="knowledge-reindex"),
    path("plans/", plan_trip_view, name="plan-trip"),
    path("plans/stream/", plan_trip_stream_view, name="plan-trip-stream"),
    path("plans/<str:run_id>/", plan_status_view, name="plan-status"),
    path("plans/<str:run_id>/save/", save_run_plan_view, name="plan-save"),
    path("chat/sessions/", chat_sessions_view, name="chat-session-list-create"),
    path("chat/sessions/recent/", recent_chat_session_view, name="chat-session-recent"),
    path("chat/sessions/<str:session_id>/", chat_session_view, name="chat-session"),
    path(
        "chat/sessions/<str:session_id>/messages/",
        create_chat_turn_view,
        name="chat-turn-create",
    ),
    path(
        "chat/sessions/<str:session_id>/messages/stream/",
        create_chat_turn_stream_view,
        name="chat-turn-create-stream",
    ),
    path(
        "chat/sessions/<str:session_id>/turns/<str:turn_id>/",
        chat_turn_view,
        name="chat-turn",
    ),
    path(
        "chat/sessions/<str:session_id>/plans/",
        save_trip_plan_view,
        name="trip-plan-save",
    ),
    path("trip-plans/", trip_plans_view, name="trip-plan-list"),
    path("trip-plans/<str:plan_id>/", trip_plan_view, name="trip-plan-detail"),
    path(
        "trip-plans/<str:plan_id>/resume/",
        resume_trip_plan_view,
        name="trip-plan-resume",
    ),
]
